 
# see https://docs.github.com/en/actions/creating_actions/metadata_syntax_for_github_actions#about_yaml_syntax_for_github_actions

name: 'Monorepo Split'
description: 'Split monorepo packages to many repositories'
author: "Andrew Mellor <andrew@quasars.com>"

inputs:
    repository_host:
        description: 'Host'
        default: 'github.com'
        required: false
    repository_organization:
        description: 'Remote organization'
        required: true
    package_list:
        description: 'JSON list of packages'
        required: true
    user_email:
        description: 'Git User Email'
        required: true
    user_name:
        description: 'Git User Name'
        required: true

runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        # "GitHub stores input parameters as environment variables" - important!!!
        - ${{ inputs.repository_host }} # => INPUT_REPOSITORY_HOST
        - ${{ inputs.repository_organization }}
        - ${{ inputs.package_list }}
        - ${{ inputs.user_email }}
        - ${{ inputs.user_name }}

branding:
    icon: maximize-2
    color: purple
