 
# see https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#about-yaml-syntax-for-github-actions

name: 'Monorepo Split'
description: 'Split monorepo packages to many repositories'
author: "Andrew Mellor <andrew@quasars.com>"

inputs:
    package-directory:
        description: 'Local package directory'
        required: true
    repository-host:
        description: 'Host'
        default: 'github.com'
        required: false
    repository-organization:
        description: 'Remote organization'
        required: true
    package-list:
        description: 'JSON list of packages'
        required: true
    branch:
        description: 'Git branch'
        default: 'main'
        required: false
    user-email:
        description: 'Git User Email'
        required: true
    user-name:
        description: 'Git User Name'
        required: true

runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        # "GitHub stores input parameters as environment variables" - important!!!
        - ${{ inputs.package-directory }} # => INPUT-PACKAGE-DIRECTORY
        - ${{ inputs.repository-host }}
        - ${{ inputs.repository-organization }}
        - ${{ inputs.package-list }}
        - ${{ inputs.branch }}
        - ${{ inputs.tag }}
        - ${{ inputs.user-email }}
        - ${{ inputs.user-name }}

branding:
    icon: maximize-2
    color: purple
